import { alerts,dashboardMetrics,hotMatches,hotUsers,marketMoves,matches } from '../services/dashboard.js';
import type { Match } from '../types/index.js';
import { badge,drawer,emptyState,loadingState,metric,pageHeader,panel,progress,segmented } from '../components/ui.js';
import { esc } from '../utils/dom.js';
export interface DashboardState{league:string;status:string;query:string;day:string;loading:boolean;selectedMatch:string|null}
const tone=(s:string)=>s==='进行中'?'live':s==='已结束'?'done':'pending';
export function renderDashboard(s:DashboardState){
 const filtered=matches.filter(m=>(s.league==='全部'||s.league===m.league||(s.league==='竞彩'&&m.category==='竞彩')||(s.league==='其他'&&m.category==='其他'))&&(s.status==='全部'||s.status===m.status)&&(!s.query||`${m.home}${m.away}${m.league}`.toLowerCase().includes(s.query.toLowerCase())));
 const leagueBtns=['全部','竞彩','英超','西甲','德甲','意甲','法甲','欧冠','其他'].map(x=>`<button data-filter="dashboard-league" data-value="${esc(x)}" class="${s.league===x?'active':''}">${esc(x)}</button>`).join('');
 const statusBtns=['全部','未开赛','进行中','已结束'].map(x=>`<button data-filter="dashboard-status" data-value="${esc(x)}" class="${s.status===x?'active':''}">${esc(x)}</button>`).join('');
 const tableBody=filtered.map(m=>`<tr><td>${esc(m.time)}</td><td><span class="league-tag">${esc(m.league)}</span></td><td><button class="link-btn" data-open-match="${m.id}">${esc(m.home)}</button></td><td class="score">${esc(m.score)}</td><td><button class="link-btn" data-open-match="${m.id}">${esc(m.away)}</button></td><td>${badge(m.status,tone(m.status))}</td><td><div class="odds-row">${m.euro.map(o=>`<span>${esc(o.label)} ${esc(o.value)} ${o.trend==='up'?'↑':o.trend==='down'?'↓':''}</span>`).join('')}</div></td><td>${esc(m.asian)}</td><td>${esc(m.totals)}</td><td>${m.plans}</td><td><span class="heat">♨ ${m.heat}</span></td><td>${m.anomaly?badge(m.anomaly,'danger'):'<span class="muted">—</span>'}</td></tr>`).join('');
 let html=pageHeader('DATA WORKSPACE','今日总览','赛事、方案、用户与盘口数据实时聚合',`${segmented(['昨日','今日','明日'],s.day,'dashboard-day')}<button class="btn">▣ 2026-08-29</button>`);
 html+=`<div class="filter-toolbar"><div class="filter-group"><span>联赛</span><div class="chips">${leagueBtns}</div></div><div class="filter-group"><span>状态</span><div class="chips">${statusBtns}</div></div><div class="toolbar-spacer"></div><div class="search-box"><span>⌕</span><input data-input="dashboard-query" value="${esc(s.query)}" placeholder="搜索球队 / 联赛"/></div><button class="btn" data-action="dashboard-loading">☷ 高级筛选</button></div>`;
 html+=`<div class="metric-grid seven">${metric('今日赛事',dashboardMetrics.matches)}${metric('进行中',dashboardMetrics.live,'','success')}${metric('今日方案',dashboardMetrics.plans.toLocaleString())}${metric('发单用户',dashboardMetrics.users)}${metric('异常盘口',dashboardMetrics.anomalies,'','danger')}${metric('热门比赛',dashboardMetrics.hot)}${metric('已完成',dashboardMetrics.completed)}</div>`;
 const eventTable=s.loading?loadingState():filtered.length?`<div class="table-wrap"><table><thead><tr><th>时间</th><th>赛事</th><th>主队</th><th>比分</th><th>客队</th><th>状态</th><th>欧赔</th><th>亚盘</th><th>大小球</th><th>方案数</th><th>热度</th><th>异常</th></tr></thead><tbody>${tableBody}</tbody></table></div>`:emptyState('没有匹配赛事');
 const moves=marketMoves.map(r=>`<div class="compact-row"><span class="time">${esc(r.time)}</span><div><b>${esc(r.match)}</b><small>${esc(r.company)} · ${esc(r.change)}</small></div>${badge(r.state,r.state==='升盘'?'danger':'success')}</div>`).join('');
 const warningRows=alerts.map(r=>`<div class="alert-row"><div><b>${esc(r.type)}</b><small>${esc(r.time)} · ${esc(r.desc)}</small></div>${badge(`${r.risk}风险`,r.risk==='高'?'danger':r.risk==='中'?'warning':'pending')}</div>`).join('');
 html+=`<div class="dashboard-grid">${panel('今日赛事',eventTable,`<span class="muted">共 ${filtered.length} 场</span>`)}<div class="side-stack">${panel('盘口异动',`<div class="compact-list">${moves}</div>`)}${panel('异常提醒',`<div class="compact-list">${warningRows}</div>`)}</div></div>`;
 const ranks=hotMatches.map((m,i)=>`<button class="rank-row" data-open-match="${m.id}"><b>#${i+1}</b><span>${esc(m.home)} <em>vs</em> ${esc(m.away)}</span><small>${esc(m.league)} · ${esc(m.time)}</small><div>${progress(m.heat)}<strong>${m.heat}</strong></div></button>`).join('');
 const userRows=hotUsers.map((u,i)=>`<div class="mini-user"><span class="avatar">${i+1}</span><div><b>${esc(u.name)}</b><small>${esc(u.platform)} · ${u.plans} 个方案</small></div><div class="mini-user-kpi"><strong>${u.winRate}%</strong><span>命中率</span></div><div class="mini-user-kpi positive"><strong>+${u.roi}%</strong><span>ROI</span></div></div>`).join('');
 html+=`<div class="bottom-grid">${panel('热门赛事 TOP10',`<div class="rank-list">${ranks}</div>`)}${panel('今日热门用户',`<div class="user-cards">${userRows}</div>`)}</div>`;
 const selected=matches.find(m=>m.id===s.selectedMatch);
 if(selected)html+=matchDrawer(selected);
 return html;
}
function matchDrawer(m:Match){return drawer('赛事详情',`<div class="detail-stack"><div class="match-hero"><div><span>${esc(m.league)}</span><h3>${esc(m.home)}</h3></div><strong>${esc(m.score)}</strong><div class="right"><span>${esc(m.time)}</span><h3>${esc(m.away)}</h3></div></div><div class="detail-grid">${metric('状态',m.status)}${metric('方案数',m.plans)}${metric('热度',m.heat)}${metric('异常',m.anomaly||'无')}</div>${panel('即时盘口',`<div class="key-values"><div><span>亚洲让球</span><b>${esc(m.asian)}</b></div><div><span>大小球</span><b>${esc(m.totals)}</b></div>${m.euro.map(x=>`<div><span>欧赔 · ${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}</div>`)}</div>`)}
