<template>
  <section class="page-shell">
    <header class="page-header"><div><h1>投注热力</h1><p>今日未截止方案 · 同一玩法内独立投注项占比</p></div><button class="primary-button" type="button" @click="load">刷新</button></header>
    <section class="play-tabs app-card"><button v-for="play in plays" :key="play" type="button" :class="{active:playType===play}" @click="changePlay(play)">{{ play }}</button></section>
    <LoadingSkeleton v-if="loading" class="section-gap" type="cards" :count="4" />
    <ErrorState v-else-if="error" class="app-card section-gap" :description="error" @retry="load" />
    <template v-else>
      <section class="focus-card app-card section-gap"><header class="section-header"><div><span class="eyebrow">Center picks</span><h2>各玩法重心分析</h2><p>按真实投注数量提取</p></div></header><div v-if="focus.length" class="focus-grid"><article v-for="item in focus" :key="item.match_code+item.match_name"><span>{{ item.match_code || "--" }}</span><h3>{{ item.match_name || "--" }}</h3><strong>{{ item.option || "--" }}</strong><b>{{ number(item.count) }} 次</b><small>占比 {{ item.share ?? "--" }}%</small></article></div><EmptyState v-else title="暂无重心数据" description="当前玩法没有可提取的比赛" /></section>
      <section class="platform-card app-card section-gap"><header class="section-header"><div><h2>平台汇总</h2><p>赛事投注项次数</p></div></header><div v-if="platformSummary.length" class="platform-grid"><article v-for="item in platformSummary" :key="item.platform_id"><span>{{ item.platform_name || "--" }}</span><strong>{{ number(item.total_items) }}</strong><div><b v-for="option in (item.options||[]).slice(0,5)" :key="option.option">{{ option.option }} {{ number(option.count) }}</b></div></article></div><EmptyState v-else title="暂无平台汇总" description="接口未返回当前玩法的平台统计" /></section>
      <section class="matrix-card app-card section-gap"><header class="section-header"><div><h2>赛事投注冷热矩阵</h2><p>{{ playType }} · {{ (data.matches||[]).length }} 场</p></div><div class="legend"><span>低</span><i></i><i></i><i></i><i></i><span>高</span></div></header><div v-if="(data.matches||[]).length" class="matrix-list"><article v-for="match in data.matches" :key="match.match_code+match.match_name"><div class="matrix-match"><span>{{ match.match_code || "--" }}</span><h3>{{ match.home || "--" }} <i>VS</i> {{ match.away || "--" }}</h3><small>{{ match.league || "--" }} · {{ number(match.total_items) }} 个投注项</small></div><div class="matrix-options"><div v-for="option in match.options||[]" :key="option.option" :style="heatStyle(option.share)"><span>{{ option.option || "--" }}</span><strong>{{ option.share ?? "--" }}%</strong><small>{{ number(option.count) }} 次</small></div></div></article></div><EmptyState v-else title="暂无热力数据" description="今日未截止订单暂无该玩法数据" /></section>
    </template>
  </section>
</template>
<script setup>
import { computed,onMounted,ref } from "vue";import axios from "axios";import LoadingSkeleton from "../components/ui/LoadingSkeleton.vue";import EmptyState from "../components/ui/EmptyState.vue";import ErrorState from "../components/ui/ErrorState.vue"
const plays=["胜平负","让球胜平负","半全场","比分"],playType=ref("胜平负"),data=ref({}),loading=ref(true),error=ref("");const focus=computed(()=>data.value.focus||[]),platformSummary=computed(()=>data.value.platform_summary||[])
async function load(){loading.value=true;error.value="";try{const r=await axios.get("/api/portal/heatmap",{params:{play_type:playType.value}});if(!r.data||r.data.code!==200)throw new Error();data.value=r.data.data||{}}catch{data.value={};error.value="热力数据暂时无法读取，请稍后重试或检查接口连接状态"}finally{loading.value=false}}
function changePlay(v){playType.value=v;load()} function number(v){return Math.round(Number(v||0)).toLocaleString("zh-CN")} function heatStyle(v){const n=Number(v||0);return{background:n>=75?"#bcd71e":n>=50?"#d9ff35":n>=25?"#ebf5a6":n>0?"#f5f8dc":"#fafaf8"}} onMounted(load)
</script>
<style scoped>
.section-gap{margin-top:14px}.play-tabs{padding:7px;display:flex;gap:5px;width:fit-content}.play-tabs button{min-height:38px;padding:0 16px;border:0;border-radius:9px;color:var(--text-secondary);background:transparent;font-size:12px;font-weight:650}.play-tabs button.active{color:var(--accent);background:var(--sidebar-bg)}.focus-card,.platform-card,.matrix-card{padding:20px}.focus-grid{margin-top:14px;display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.focus-grid article{padding:15px;border:1px solid var(--border);border-radius:13px;background:var(--surface-soft)}.focus-grid span,.focus-grid strong,.focus-grid b,.focus-grid small{display:block}.focus-grid span,.focus-grid small{color:var(--text-muted);font-size:10px}.focus-grid h3{min-height:34px;margin:7px 0 12px;font-size:12px}.focus-grid strong{font-size:18px}.focus-grid b{margin-top:5px;color:#6f810e;font-size:12px}.focus-grid small{margin-top:5px}.platform-grid{margin-top:14px;display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:9px}.platform-grid article{padding:14px;border-radius:12px;background:var(--surface-soft)}.platform-grid article>span{color:var(--text-muted);font-size:11px}.platform-grid article>strong{display:block;margin-top:4px;font-size:25px}.platform-grid article>div{margin-top:9px;display:flex;flex-wrap:wrap;gap:5px}.platform-grid b{padding:4px 6px;border-radius:6px;background:#fff;font-size:9px}.legend{display:flex;align-items:center;gap:4px;color:var(--text-muted);font-size:9px}.legend i{width:18px;height:10px;border-radius:3px}.legend i:nth-of-type(1){background:#f5f8dc}.legend i:nth-of-type(2){background:#ebf5a6}.legend i:nth-of-type(3){background:#d9ff35}.legend i:nth-of-type(4){background:#bcd71e}.matrix-list{margin-top:14px;display:grid;gap:8px}.matrix-list>article{padding:13px;border:1px solid var(--border);border-radius:13px;display:grid;grid-template-columns:minmax(230px,.7fr) minmax(0,1.3fr);gap:14px}.matrix-match>span{color:#70830e;font-size:10px;font-weight:700}.matrix-match h3{margin:6px 0 4px;font-size:13px}.matrix-match h3 i{margin:0 4px;color:var(--text-muted);font-size:9px;font-style:normal}.matrix-match small{color:var(--text-muted);font-size:10px}.matrix-options{display:grid;grid-template-columns:repeat(auto-fit,minmax(95px,1fr));gap:6px}.matrix-options>div{min-height:72px;padding:10px;border-radius:10px;color:var(--text-main)}.matrix-options span,.matrix-options strong,.matrix-options small{display:block}.matrix-options span{font-size:10px}.matrix-options strong{margin-top:3px;font-size:18px}.matrix-options small{margin-top:2px;font-size:9px;opacity:.68}@media(max-width:900px){.focus-grid{grid-template-columns:repeat(2,1fr)}.matrix-list>article{grid-template-columns:1fr}}@media(max-width:520px){.play-tabs{width:100%;overflow-x:auto}.play-tabs button{white-space:nowrap}.focus-grid{grid-template-columns:1fr}}
</style>
