<template>
  <section class="page-shell">
    <header class="page-header"><div><button class="back-link" type="button" @click="router.back()">← 返回</button><h1>订单详情</h1><p>{{ order.platform_name || "--" }} · 订单号 {{ order.platform_order_id || order.id || "--" }}</p></div></header>
    <LoadingSkeleton v-if="loading" type="cards" :count="4"/><ErrorState v-else-if="error" class="app-card" :description="error" @retry="load"/>
    <template v-else><section class="order-profile app-card"><div><span>发单人</span><strong>{{ order.nickname || "--" }}</strong></div><div><span>发单时间</span><strong>{{ time(order.publish_time) }}</strong></div><div><span>自购</span><strong>¥{{ money(order.stake) }}</strong></div><div><span>跟单</span><strong>{{ number(order.follow_num) }}</strong></div><div><span>回报</span><strong>{{ order.return_amount===null||order.return_amount===undefined?"--":"¥"+money(order.return_amount) }}</strong></div><div><span>串关</span><strong>{{ order.pass_composition || passText(order) }}</strong></div><div><span>状态</span><span :class="resultClass(order.result)">{{ resultText(order.result) }}</span></div></section>
      <section class="legs-card app-card"><header class="section-header"><div><h2>比赛明细</h2><p>仅展示接口真实提供的比赛字段</p></div></header><div v-if="(order.matches||[]).length" class="table-wrap"><table class="data-table legs-table"><thead><tr><th>编号</th><th>球队</th><th>时间</th><th>玩法</th><th>让球</th><th>选择</th><th>赔率</th><th>赛果</th><th>比分</th><th>单腿结果</th></tr></thead><tbody><tr v-for="match in order.matches" :key="match.id"><td>{{ match.match_code || "--" }}</td><td><b class="teams">{{ match.home || "--" }} <i>VS</i> {{ match.away || "--" }}</b></td><td>{{ time(match.match_time) }}</td><td>{{ match.play_type || "--" }}</td><td>{{ match.handicap===null||match.handicap===undefined?"--":match.handicap }}</td><td>{{ match.selection || "--" }}</td><td>{{ match.odds===null||match.odds===undefined?"--":match.odds }}</td><td>{{ match.match_status || "--" }}</td><td>{{ fullScore(match) }}</td><td><span :class="resultClass(match.result)">{{ resultText(match.result) }}</span></td></tr></tbody></table></div><EmptyState v-else title="暂无比赛明细" description="当前订单尚未生成拆分比赛数据"/></section>
    </template>
  </section>
</template>
<script setup>
import { onMounted,ref } from "vue";import { useRoute,useRouter } from "vue-router";import axios from "axios";import LoadingSkeleton from "../components/ui/LoadingSkeleton.vue";import EmptyState from "../components/ui/EmptyState.vue";import ErrorState from "../components/ui/ErrorState.vue"
const route=useRoute(),router=useRouter(),order=ref({}),loading=ref(true),error=ref("")
async function load(){loading.value=true;error.value="";try{const r=await axios.get("/api/portal/order/"+route.params.id);if(!r.data||r.data.code!==200)throw new Error();order.value=r.data.data||{}}catch{order.value={};error.value="订单详情暂时无法读取，请稍后重试或检查接口连接状态"}finally{loading.value=false}}
function money(v){return Number(v||0).toLocaleString("zh-CN",{maximumFractionDigits:2})}function number(v){return Math.round(Number(v||0)).toLocaleString("zh-CN")}function time(v){return v?String(v).replace("T"," ").replace("Z",""):"--"}function passText(o){const c=Number(o.bet_count||0),p=o.pass_summary||"--";return c>0?c+"注"+p:p}function resultText(v){return v==="赢"?"已中奖":v==="输"?"未中奖":v||"待开奖"}function resultClass(v){return "status-chip "+(v==="赢"?"success":v==="输"?"danger":"warning")}function fullScore(m){if(m.home_score===null||m.home_score===undefined||m.away_score===null||m.away_score===undefined)return "--";let t=m.home_score+":"+m.away_score;if(m.half_home_score!==null&&m.half_home_score!==undefined&&m.half_away_score!==null&&m.half_away_score!==undefined)t+=" / 半 "+m.half_home_score+":"+m.half_away_score;return t}onMounted(load)
</script>
<style scoped>
.back-link{margin-bottom:9px;padding:0;border:0;color:var(--text-secondary);background:transparent;font-size:12px}.order-profile{padding:13px;display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.order-profile>div{min-width:0;padding:13px;border-radius:11px;background:var(--surface-soft)}.order-profile span,.order-profile strong{display:block}.order-profile>div>span:first-child{color:var(--text-muted);font-size:10px}.order-profile strong{margin-top:7px;overflow:hidden;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.order-profile .status-chip{margin-top:7px}.legs-card{margin-top:14px;padding:19px;overflow:hidden}.legs-card .table-wrap{margin:14px -19px -19px}.legs-table{min-width:1200px}.teams{color:var(--text-main)}.teams i{margin:0 5px;color:var(--text-muted);font-size:9px;font-style:normal}@media(max-width:1050px){.order-profile{grid-template-columns:repeat(4,1fr)}}@media(max-width:650px){.order-profile{grid-template-columns:repeat(2,1fr)}}@media(max-width:420px){.order-profile{grid-template-columns:1fr}}
</style>
