<template>
  <section class="page-shell detail-page">
    <header class="page-header"><div><router-link class="back-link" to="/match-data">← 返回水位看板</router-link><h1>{{ match.home || "比赛详情" }} <span v-if="match.away">VS {{ match.away }}</span></h1><p>{{ match.competition || "赛事待同步" }} · {{ match.code || match.externalId || "--" }}</p></div><router-link class="secondary-button news-link" :to="`/match-news?match=${encodeURIComponent(route.params.externalId)}`">查看比赛新闻</router-link></header>
    <section class="source-bar app-card"><span><b>{{ statusText }}</b><i>更新于 {{ formatTime(data.updatedAt) }}</i></span><small>数据来源：公开网络数据 / scpai.top</small></section>
    <LoadingSkeleton v-if="loading" class="section-gap" type="cards" :count="5" />
    <ErrorState v-else-if="error" class="app-card section-gap" :description="error" @retry="load" />
    <template v-else>
      <section v-if="markets.length" class="market-grid section-gap"><button v-for="market in markets" :key="market.id" type="button" class="market-card app-card" :class="{selected:selectedMarket?.id===market.id}" @click="selectedId=market.id"><header><span>{{ market.name || marketName(market.type) }}</span><b>{{ market.directionLabel || market.directionKey || "--" }}</b></header><strong>{{ market.selection || "--" }}</strong><div><span>当前 {{ market.currentOdd ?? "--" }}</span><span>初始 {{ market.openingOdd ?? "--" }}</span><span>变化 {{ market.delta ?? "--" }}</span></div><footer><span>{{ market.line ?? "盘口待同步" }}</span><em :class="{on:market.synchronized}">{{ market.synchronized ? "已同步" : "待同步" }}</em></footer></button></section>
      <EmptyState v-else class="app-card section-gap" title="暂无盘口数据" description="该比赛暂未返回公开盘口序列" />
      <section v-if="selectedMarket" class="chart-card app-card section-gap"><header class="section-header"><div><span class="eyebrow">Market movement</span><h2>{{ selectedMarket.name || marketName(selectedMarket.type) }} 水位曲线</h2><p>概率与赔率变化由公开序列绘制</p></div><span class="status-chip">{{ selectedMarket.rawMarketId }}</span></header><div ref="chartElement" class="chart" role="img" aria-label="盘口变化折线图"></div></section>
      <section class="context-grid section-gap"><article v-for="side in teamSides" :key="side.key" class="team-card app-card"><span class="eyebrow">{{ side.label }}</span><h2>{{ side.data.team || side.data.label || "球队数据待同步" }}</h2><div class="team-stats"><span><b>{{ side.data.position ?? "--" }}</b>排名</span><span><b>{{ side.data.points ?? "--" }}</b>积分</span><span><b>{{ side.data.played ?? "--" }}</b>场次</span><span><b>{{ side.data.wins ?? "--" }}</b>胜</span></div><p>{{ side.data.motivation?.detail || side.data.motivation?.label || "暂无战意说明" }}</p><small v-if="side.data.form">近期 {{ side.data.form }}</small></article></section>
      <section class="absence-card app-card section-gap"><header class="section-header"><div><span class="eyebrow">Availability</span><h2>伤停信息</h2></div><span class="status-chip">{{ context.absenceStatus || "状态待同步" }}</span></header><div v-if="context.absences?.length" class="absence-list"><article v-for="(item,index) in context.absences" :key="index"><b>{{ item.player || "球员待同步" }}</b><span>{{ item.side || item.team || "--" }}</span><p>{{ item.reason || "原因待同步" }}</p><small>{{ item.source || "公开来源" }}</small></article></div><EmptyState v-else title="暂无已确认伤停信息" description="空数组表示当前公开数据未确认伤停，并非接口错误" /></section>
    </template>
  </section>
</template>
<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue"
import { useRoute } from "vue-router"
import axios from "axios"
import * as echarts from "echarts"
import EmptyState from "../components/ui/EmptyState.vue"
import ErrorState from "../components/ui/ErrorState.vue"
import LoadingSkeleton from "../components/ui/LoadingSkeleton.vue"
const route=useRoute(),data=ref({}),loading=ref(true),error=ref(""),selectedId=ref(""),chartElement=ref(null);let chart=null
const match=computed(()=>data.value.match||{}),markets=computed(()=>Array.isArray(data.value.markets)?data.value.markets:[]),context=computed(()=>data.value.context||{}),selectedMarket=computed(()=>markets.value.find(item=>item.id===selectedId.value)||markets.value[0]||null),teamSides=computed(()=>[{key:"home",label:"主队基本面",data:context.value.home||{}},{key:"away",label:"客队基本面",data:context.value.away||{}}]),statusText=computed(()=>({fresh:"数据已更新",cached:"使用缓存数据",stale:"显示最近缓存数据",unavailable:"数据暂不可用"}[data.value.status]||"公开比赛详情"))
async function load(){loading.value=true;error.value="";try{const response=await axios.get(`/api/matches/${encodeURIComponent(route.params.externalId)}`);data.value=response.data?.data||{};selectedId.value=markets.value[0]?.id||""}catch(errorValue){data.value={};error.value=errorValue.response?.data?.msg||"比赛详情暂时无法读取"}finally{loading.value=false;await nextTick();renderChart()}}
function renderChart(){if(!chartElement.value||!selectedMarket.value)return;chart=chart||echarts.init(chartElement.value);chart.setOption({grid:{left:45,right:22,top:25,bottom:35},tooltip:{trigger:"axis"},xAxis:{type:"category",data:selectedMarket.value.labels||[],axisLine:{lineStyle:{color:"#d9d9d3"}},axisLabel:{color:"#85858a"}},yAxis:{type:"value",scale:true,splitLine:{lineStyle:{color:"#eeeeea"}},axisLabel:{color:"#85858a"}},series:[{type:"line",smooth:true,symbol:"circle",symbolSize:7,data:selectedMarket.value.values||[],lineStyle:{width:3,color:"#7f9412"},itemStyle:{color:"#d9ff35",borderColor:"#252527",borderWidth:2},areaStyle:{color:"rgba(217,255,53,.16)"}}]})}
function resize(){chart?.resize()} function formatTime(value){if(!value)return "时间待同步";const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleString("zh-CN",{hour12:false})} function marketName(type){return({WIN_DRAW_LOSS:"胜平负",HANDICAP_1X2:"让球胜平负",ASIAN_HANDICAP:"亚洲让球",OVER_UNDER:"大小球",BOTH_TEAMS_TO_SCORE:"双方进球",UNKNOWN:"其他盘口"}[type]||"盘口")}
watch(selectedMarket,async()=>{await nextTick();renderChart()});onMounted(()=>{load();window.addEventListener("resize",resize)});onBeforeUnmount(()=>{window.removeEventListener("resize",resize);chart?.dispose()})
</script>
<style scoped>
.back-link{display:inline-block;margin-bottom:8px;color:#74860f;font-size:12px;font-weight:700}.page-header h1 span{font-weight:500}.news-link{display:inline-flex;align-items:center}.source-bar{padding:12px 15px;display:flex;justify-content:space-between;color:var(--text-muted);font-size:11px}.source-bar span{display:flex;gap:10px}.source-bar b{color:var(--text-secondary)}.section-gap{margin-top:14px}.market-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.market-card{padding:14px;text-align:left}.market-card.selected{border-color:#a9c51e;box-shadow:0 0 0 2px rgba(217,255,53,.2)}.market-card header,.market-card footer,.market-card>div{display:flex;justify-content:space-between;gap:6px}.market-card header{color:var(--text-muted);font-size:10px}.market-card header b{color:#758811}.market-card>strong{display:block;margin:13px 0;font-size:18px}.market-card>div{color:var(--text-secondary);font-size:9px}.market-card footer{margin-top:11px;padding-top:10px;border-top:1px solid var(--border);font-size:9px}.market-card em{color:var(--text-muted);font-style:normal}.market-card em.on{color:var(--success)}.chart-card{padding:20px}.chart{height:330px;margin-top:10px}.context-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.team-card{padding:20px}.team-card h2{margin:0 0 14px}.team-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.team-stats span{padding:10px;border-radius:10px;color:var(--text-muted);background:var(--surface-soft);font-size:9px}.team-stats b{display:block;margin-bottom:3px;color:var(--text-main);font-size:19px}.team-card p{min-height:38px;color:var(--text-secondary);font-size:12px;line-height:1.6}.team-card small{color:#74860f}.absence-card{padding:20px}.absence-list{margin-top:16px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.absence-list article{padding:13px;border-radius:11px;background:var(--surface-soft)}.absence-list b,.absence-list span,.absence-list small{display:block}.absence-list span,.absence-list small{margin-top:4px;color:var(--text-muted);font-size:10px}.absence-list p{font-size:11px}@media(max-width:1200px){.market-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.source-bar,.source-bar span{align-items:flex-start;flex-direction:column}.market-grid,.context-grid,.absence-list{grid-template-columns:1fr}.chart{height:260px}}
</style>
