<template>
  <section class="page-shell">
    <header class="page-header"><div><h1>用户中心</h1><p>跨平台发单用户表现与真实统计</p></div><button class="primary-button" type="button" @click="load">刷新</button></header>
    <section class="grade-grid"><article class="app-card"><span>S 级</span><strong>--</strong><small>接口未提供等级汇总</small></article><article class="app-card"><span>A 级</span><strong>--</strong><small>接口未提供等级汇总</small></article><article class="app-card"><span>B 级</span><strong>--</strong><small>接口未提供等级汇总</small></article><article class="app-card dark"><span>用户总数</span><strong>{{ number(total) }}</strong><small>当前查询结果</small></article></section>
    <section class="toolbar app-card section-gap"><select v-model="platform" aria-label="平台" @change="resetLoad"><option value="">全部平台</option><option v-for="item in platforms" :key="item.platform_id" :value="String(item.platform_id)">{{ item.name }}</option></select><input v-model.trim="keyword" class="search" placeholder="用户名 / 用户 ID" @keyup.enter="resetLoad"><select v-model="sort" aria-label="排序" @change="resetLoad"><option value="score">综合分</option><option value="orders">发单数</option><option value="hit">命中率</option><option value="profit">盈利</option><option value="roi">ROI</option><option value="follow">跟单人数</option></select><button class="primary-button" type="button" @click="resetLoad">查询</button></section>
    <section class="users-card app-card section-gap"><LoadingSkeleton v-if="loading" :count="8"/><ErrorState v-else-if="error" :description="error" @retry="load"/><EmptyState v-else-if="!users.length" title="暂无用户" description="当前筛选条件下没有用户数据"/><div v-else class="table-wrap"><table class="data-table users-table"><thead><tr><th>排名</th><th>用户</th><th>平台</th><th>标签</th><th>评分</th><th>7日自购</th><th>跟单</th><th>发单</th><th>盈利</th><th>命中</th><th>近期</th></tr></thead><tbody><tr v-for="item in users" :key="item.platform_id+'-'+item.user_id" tabindex="0" @click="openUser(item)" @keyup.enter="openUser(item)"><td><span class="rank" :class="{'first':item.rank===1}">{{ item.rank }}</span></td><td><div class="user-name"><img v-if="item.avatar_url" class="avatar" :src="item.avatar_url" alt=""><span v-else class="avatar-fallback">{{ avatarText(item.nickname) }}</span><span><b>{{ item.nickname || "--" }}</b><small>ID {{ item.user_id || "--" }}</small></span></div></td><td>{{ item.platform_name || "--" }}</td><td>--</td><td><strong>{{ fixed(item.expert_score) }}</strong></td><td>--</td><td>{{ number(item.follow_num) }}</td><td>{{ number(item.total_orders) }}</td><td :class="Number(item.total_profit)>=0?'money-positive':'money-negative'">{{ profit(item.total_profit) }}</td><td>{{ percent(item.hit_rate) }}</td><td>--</td></tr></tbody></table></div></section>
    <AppPagination :page="page" :pages="pages" :disabled="loading" @change="changePage"/>
  </section>
</template>
<script setup>
import { onMounted,ref } from "vue";import { useRouter } from "vue-router";import axios from "axios";import LoadingSkeleton from "../components/ui/LoadingSkeleton.vue";import EmptyState from "../components/ui/EmptyState.vue";import ErrorState from "../components/ui/ErrorState.vue";import AppPagination from "../components/ui/AppPagination.vue"
const router=useRouter(),platform=ref(""),keyword=ref(""),sort=ref("score"),users=ref([]),platforms=ref([]),page=ref(1),pages=ref(1),total=ref(0),loading=ref(true),error=ref("")
async function loadPlatforms(){try{const r=await axios.get("/api/platform/list",{timeout:25000});const rows=r.data&&r.data.data;platforms.value=Array.isArray(rows)?rows:[]}catch{platforms.value=[]}}
async function load(){loading.value=true;error.value="";const params={keyword:keyword.value,sort:sort.value,page:page.value,page_size:30};if(platform.value)params.platform_id=Number(platform.value);try{const r=await axios.get("/api/portal/users",{params,timeout:25000});if(!r.data||r.data.code!==200)throw new Error();users.value=r.data.data||[];page.value=r.data.page||1;pages.value=r.data.pages||1;total.value=r.data.total||0}catch{users.value=[];total.value=0;error.value="用户数据暂时无法读取，请稍后重试或检查接口连接状态"}finally{loading.value=false}}
function resetLoad(){page.value=1;load()}function changePage(v){page.value=v;load()}function openUser(i){router.push("/user/detail/"+i.platform_id+"/"+i.user_id)}function avatarText(v){return String(v||"球").slice(-1)}function number(v){return Math.round(Number(v||0)).toLocaleString("zh-CN")}function fixed(v){return v===null||v===undefined?"--":Number(v).toFixed(2)}function percent(v){return v===null||v===undefined?"--":Number(v).toFixed(2)+"%"}function money(v){return Number(v||0).toLocaleString("zh-CN",{maximumFractionDigits:2})}function profit(v){const n=Number(v||0);return(n>0?"+¥":n<0?"-¥":"¥")+money(Math.abs(n))}onMounted(()=>{loadPlatforms();load()})
</script>
<style scoped>
.grade-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grade-grid article{padding:17px}.grade-grid span,.grade-grid strong,.grade-grid small{display:block}.grade-grid span{color:var(--text-secondary);font-size:11px}.grade-grid strong{margin-top:8px;font-size:28px}.grade-grid small{margin-top:6px;color:var(--text-muted);font-size:9px}.grade-grid .dark{color:#fff;border-color:#242426;background:#242426}.grade-grid .dark span,.grade-grid .dark small{color:#aaaab0}.section-gap{margin-top:14px}.toolbar .search{min-width:260px;flex:1}.users-card{overflow:hidden}.users-table{min-width:1080px}.users-table tbody tr{cursor:pointer}.rank{width:26px;height:26px;border-radius:8px;display:grid;place-items:center;background:#f1f1ee;font-size:10px;font-weight:700}.rank.first{background:var(--accent)}.user-name{display:flex;align-items:center;gap:9px;min-width:190px}.user-name>span:last-child{min-width:0}.user-name b,.user-name small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.user-name b{color:var(--text-main)}.user-name small{margin-top:3px;color:var(--text-muted);font-size:10px}@media(max-width:800px){.grade-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.grade-grid{grid-template-columns:1fr}.toolbar>*{width:100%}.toolbar .search{min-width:0}}
</style>
