<template>
  <section class="page-shell">
    <header class="page-header"><div><button class="back-link" type="button" @click="router.back()">← 返回</button><h1>用户详情</h1><p>平台用户档案与历史方案</p></div></header>
    <LoadingSkeleton v-if="loading" type="cards" :count="4" />
    <ErrorState v-else-if="error" class="app-card" :description="error" @retry="load" />
    <template v-else>
      <section class="profile-card app-card"><img v-if="user.avatar_url" class="profile-avatar" :src="user.avatar_url" alt=""><span v-else class="profile-avatar avatar-fallback">{{ avatarText(user.nickname) }}</span><div><span class="eyebrow">User profile</span><h2>{{ user.nickname || "--" }}</h2><p>{{ user.platform_name || "--" }} · ID {{ user.user_id || "--" }}</p></div><span class="score-tag">综合评分 {{ fixed(user.expert_score) }}</span></section>
      <section class="profile-kpis"><article class="app-card"><span>历史战绩</span><strong>{{ number(user.win_orders) }}胜 {{ number(user.lose_orders) }}负</strong><small>命中率 {{ percent(user.hit_rate) }}</small></article><article class="app-card"><span>自购金额</span><strong>¥{{ money(user.total_stake) }}</strong><small>累计投注</small></article><article class="app-card"><span>跟单人数</span><strong>{{ number(user.follow_num) }}</strong><small>累计人次</small></article><article class="app-card"><span>累计盈利</span><strong :class="Number(user.total_profit)>=0?'money-positive':'money-negative'">{{ profit(user.total_profit) }}</strong><small>ROI {{ percent(user.roi) }}</small></article></section>
      <section class="history-card app-card"><header class="section-header"><div><h2>历史订单</h2><p>接口返回的用户方案记录</p></div><span>{{ orders.length }} 条</span></header><div v-if="orders.length" class="history-list"><article v-for="order in orders" :key="order.id" tabindex="0" @click="openOrder(order.id)" @keyup.enter="openOrder(order.id)"><header><div><b>{{ order.platform_order_id || order.id || "--" }}</b><small>{{ time(order.publish_time) }}</small></div><span :class="resultClass(order.result)">{{ resultText(order.result) }}</span></header><div class="history-facts"><span>串关 <b>{{ order.pass_composition || passText(order) }}</b></span><span>自购 <b>¥{{ money(order.stake) }}</b></span><span>中奖 <b>¥{{ money(order.bonus) }}</b></span></div><div class="history-matches"><div v-for="match in order.matches||[]" :key="match.id"><b>{{ match.match_code || "--" }} · {{ match.home || "--" }} VS {{ match.away || "--" }}</b><span>{{ match.play_type || "--" }} · {{ match.selection || "--" }} · {{ match.result || "待开奖" }} {{ scoreText(match) }}</span></div></div></article></div><EmptyState v-else title="暂无历史订单" description="该用户暂时没有可展示的方案记录" /></section>
    </template>
  </section>
</template>
<script setup>
import { onMounted,ref,watch } from "vue";import { useRoute,useRouter } from "vue-router";import axios from "axios";import LoadingSkeleton from "../components/ui/LoadingSkeleton.vue";import EmptyState from "../components/ui/EmptyState.vue";import ErrorState from "../components/ui/ErrorState.vue"
const route=useRoute(),router=useRouter(),user=ref({}),orders=ref([]),loading=ref(true),error=ref("")
async function load(){loading.value=true;error.value="";try{const r=await axios.get("/api/portal/user/"+route.params.platform+"/"+route.params.id);if(!r.data||r.data.code!==200)throw new Error();user.value=r.data.data.user||{};orders.value=r.data.data.orders||[]}catch{user.value={};orders.value=[];error.value="用户详情暂时无法读取，请稍后重试或检查接口连接状态"}finally{loading.value=false}}
function openOrder(id){router.push("/order/detail/"+id)}function avatarText(v){return String(v||"球").slice(-1)}function number(v){return Math.round(Number(v||0)).toLocaleString("zh-CN")}function money(v){return Number(v||0).toLocaleString("zh-CN",{maximumFractionDigits:2})}function fixed(v){return v===null||v===undefined?"--":Number(v).toFixed(2)}function percent(v){return v===null||v===undefined?"--":Number(v).toFixed(2)+"%"}function profit(v){const n=Number(v||0);return(n>0?"+¥":n<0?"-¥":"¥")+money(Math.abs(n))}function time(v){return v?String(v).replace("T"," ").replace("Z",""):"--"}function passText(o){const c=Number(o.bet_count||0),p=o.pass_summary||"--";return c>0?c+"注"+p:p}function resultText(v){return v==="赢"?"已中奖":v==="输"?"未中奖":v||"待开奖"}function resultClass(v){return "status-chip "+(v==="赢"?"success":v==="输"?"danger":"warning")}function scoreText(m){return m.home_score===null||m.home_score===undefined||m.away_score===null||m.away_score===undefined?"":"· "+m.home_score+":"+m.away_score}
watch(()=>route.fullPath,load);onMounted(load)
</script>
<style scoped>
.back-link{margin-bottom:9px;padding:0;border:0;color:var(--text-secondary);background:transparent;font-size:12px}.profile-card{min-height:135px;padding:22px;display:flex;align-items:center;gap:14px}.profile-avatar{width:66px;height:66px;flex:0 0 66px;border-radius:50%;object-fit:cover}.profile-card>div{min-width:0;flex:1}.profile-card h2{margin:0;font-size:23px}.profile-card p{margin:5px 0 0;color:var(--text-muted);font-size:12px}.score-tag{padding:7px 10px;border-radius:9px;background:var(--accent-soft);font-size:11px;font-weight:650}.profile-kpis{margin-top:13px;display:grid;grid-template-columns:repeat(4,1fr);gap:11px}.profile-kpis article{padding:17px}.profile-kpis span,.profile-kpis strong,.profile-kpis small{display:block}.profile-kpis span,.profile-kpis small{color:var(--text-muted);font-size:10px}.profile-kpis strong{margin:8px 0 5px;font-size:17px}.history-card{margin-top:14px;padding:19px}.history-card>.section-header>span{color:var(--text-muted);font-size:11px}.history-list{margin-top:14px;display:grid;gap:9px}.history-list>article{padding:14px;border:1px solid var(--border);border-radius:13px;cursor:pointer;transition:border-color 150ms,box-shadow 150ms}.history-list>article:hover{border-color:var(--border-strong);box-shadow:var(--shadow-card)}.history-list article>header{display:flex;justify-content:space-between;gap:10px}.history-list header b,.history-list header small{display:block}.history-list header small{margin-top:4px;color:var(--text-muted);font-size:10px}.history-facts{margin:11px 0;padding:9px;display:flex;flex-wrap:wrap;gap:18px;border-radius:9px;background:var(--surface-soft);color:var(--text-muted);font-size:10px}.history-facts b{color:var(--text-main)}.history-matches{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.history-matches>div{padding:9px;border-left:2px solid var(--accent);background:#fafbf4}.history-matches b,.history-matches span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.history-matches b{font-size:11px}.history-matches span{margin-top:3px;color:var(--text-muted);font-size:9px}@media(max-width:850px){.profile-kpis{grid-template-columns:repeat(2,1fr)}.history-matches{grid-template-columns:1fr}}@media(max-width:520px){.profile-card{align-items:flex-start;flex-wrap:wrap}.score-tag{margin-left:80px}.profile-kpis{grid-template-columns:1fr}}
</style>
